# Publish GitHub Pages
# azure-pipelines.yml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: Credentials
  - name: USERNAME
    value: FriendlyUser
  - name: githubRepo
    value: FriendlyUser/dli-postGrad-docs

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '10.x' # replace this value with the version that you need for your project

- script: |
    npm install
    npx saber build
  displayName: 'Build and commit pages'

- script: |
    mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
    chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    ls
    cd public
    ls
    git init
    git config --local user.name "Azure Pipelines"
    git config --local user.email "azuredevops@microsoft.com"
    git add .
    git commit -m "Publishing GitHub Pages  ***NO_CI***"
    git remote add origin  https://$(USERNAME):$(GITHUB_TOKEN)@github.com/$(USERNAME)/$(githubRepo).git
    git push origin HEAD:refs/heads/gh-pages --force
  displayName: 'Publish GitHub Pages'
  condition: |
    and(not(eq(variables['Build.Reason'], 'PullRequest')),
        eq(variables['Build.SourceBranch'], 'refs/heads/master'))
